### ISSUE TITLE
Battle Brothers Heroes Crash

### ISSUE THREAD

**Issue by mmoyen** [sprutton1/GrimdarkFutureBattlescribe#100]
Attempting to add a “hero” (regular, not prime) crashes BattleScribe entirely. You can add Prime heroes just not standard ones. This is on iOS 14.1. Have not yet tried a desktop version.

**Comment by Darguth** [comment]
@mmoyen I did a major overhaul of the Battle Bros list, can you check to see if this is still an issue with the latest update?

**Comment by mmoyen** [comment]
So far seems to be fixed! Dividing up the Prime and Brothers lists was a good move too. Will let you know if I find additional errors but this seems resolved.
