### ISSUE TITLE
[Join Request] I'd like to help maintain the files

### ISSUE THREAD

**Issue by Mad-Spy** [sprutton1/GrimdarkFutureBattlescribe#132]
I'd like to help with maintaining the files. 

I can also set up the repo to be hosted direct from Github and get it on the new Battlescribe data hosting server to save on costs for whoever is hosting it now.

I'm on the OPR Discord as @Mad_Spy.

**Comment by Darguth** [comment]
@Mad-Spy sent you an invite via Discord.
