### ISSUE TITLE
Coding language

### ISSUE THREAD

**Issue by cawhittaker** [sprutton1/GrimdarkFutureBattlescribe#144]
What language you using for this, as i would like to help

**Comment by Darguth** [comment]
@cawhittaker The files are primarily XML, but you don't really need to do the scripting as the built-in Battlescribe Data Editor app will abstract it behind a GUI for you.

**Comment by Darguth** [comment]
@cawhittaker I'm organizing a Discord server around building up a group of contributors for this project. Message me @Darguth#9001 if you'd like to join.
