### ISSUE TITLE
Dwarf Guild options malfunctioning 

### ISSUE THREAD

**Issue by Phinmagic** [sprutton1/GrimdarkFutureBattlescribe#149]
When you try and choose upgrades in the Dwarf Guild lists, the radio button doesn't allow you to go to the advanced options. This is the mobile app for Android.

**Comment by Darguth** [comment]
@Phinmagic I use Dwarf Guilds as one of my primary armies and have not ran into this. Can you be more specific about what exactly you're trying to do that isn't working?

**Comment by Phinmagic** [comment]
![Screenshot_20210823-132555](https://user-images.githubusercontent.com/89406048/130490888-a5b7a5ff-b768-4d9c-b2e2-6101ae7b2a55.jpg)
![Screenshot_20210823-132603](https://user-images.githubusercontent.com/89406048/130490910-b875b3dd-8163-4b5d-94c5-f13c3501c4be.jpg)
When I try to click on the radio button to choose a pistol it doesn't open the next screen.

**Comment by Darguth** [comment]
@Phinmagic clicking on the radio button will allow you switch between the two parent-level options of AR+CCW(A1) and Pistol+CCW(A2). However, once those are selected, if you click on upgrade options itself (the text area, not the radio button) you can dive further into the details.

I'm revamping the Dwarf Guilds list which will change this layout, but it's functional as-is just not totally intuitive.

**Comment by Darguth** [comment]
Also, @Phinmagic just so you know these repos are being deprecated in favor of these in the not too distant future: https://github.com/OnePageRules

**Comment by Phinmagic** [comment]
Neither the button or the text do anything for me.
I look forward to the new file! Thanks!!

**Comment by Darguth** [comment]
I just tried this on my own Android device, and if I select a Guild Lord, give him the Pistol + CCW(A2) parent option and then click on this highlighted area of the menu:
![image](https://user-images.githubusercontent.com/8975633/130496754-0a733809-f8f9-4420-a1f9-7cf9a012608e.png)

It then brings up this sub-menu where you can select further upgrade selections:
![image](https://user-images.githubusercontent.com/8975633/130496806-c37c5982-d068-4024-a5ec-02e14b6e4187.png)

**Comment by Phinmagic** [comment]
Ok. It's working, now. I re-installed Battlescribe from Google, and relinked the repository from the list, I didn't have GDF in the list before, I was copying and pasting it into the search tool in BS. Thanks so much for all your help!
