### ISSUE TITLE
New Army: Soul-Snatchers

### ISSUE THREAD

**Issue by sprutton1** [sprutton1/GrimdarkFutureBattlescribe#27]

**Comment by Darguth** [comment]
@sprutton1 if you want to assign this to me, I'm going to take a crack at building this next.

**Comment by Darguth** [comment]
@sprutton1 Doesn't look like I can close this issue, even though it's assigned to me. But it should be done with that last PR merge.

**Comment by sprutton1** [comment]
I'll close it.

I should have caught this on the PRs, but you can add `Closes: #27` to the description and it will automatically close the issue when the PR is merged.
