### ISSUE TITLE
Combined Change Brothers unit points error for Havoc Brothers

### ISSUE THREAD

**Issue by 16-Bits** [sprutton1/GrimdarkFutureBattlescribe#78]
When using the combined unit size for Changed Brothers of the Havoc Brothers with the Disciples of Change selection, the point cost should be doubled but is not
![changebros](https://user-images.githubusercontent.com/26033112/86230963-aa732880-bb46-11ea-95dd-a85a63b7e02a.png)

**Comment by sprutton1** [comment]
@Darguth Thought you would want to know about this

**Comment by Darguth** [comment]
@sprutton1 thanks, there's also a small bug with Alien Hive weapon profiles that someone brought up on the Discord. I have an open branch to do the Psyker updates still and I'll fix both of these at the same time.

**Comment by Darguth** [comment]
@sprutton1 this was fixed in the last PR
