### ISSUE TITLE
Prime Brothers - Anti-Grav APC - Missile Array upgrade points error

### ISSUE THREAD

**Issue by Oriskana** [sprutton1/GrimdarkFutureBattlescribe#79]
Hi,

Prime Brothers - Anti-Grav APC - Missile Array upgrade is priced at 14 550 points. It should be only 145 as per GF - Prime Brothers v2.11..

**Comment by sprutton1** [comment]
@Darguth ^

**Comment by Darguth** [comment]
@sprutton1 this was fixed in the last PR
